<?php $IMPORT_ORE = array(
"Enriched Uranium",
"Supertensile Plastics",
"Oxides",
"Test Cultures",
"Polyaramids",
"Microfiber Shielding",
"Water-Cooled CPU",
"Biocells",
"Condensates",
"Camera Drones",
"Synthetic Synapses",
"Gel-Matrix Biopaste",
"Supercomputers",
"Smartfab Units",
"Nuclear Reactors",
"Neocoms",
"Biotech Research Reports",
"Industrial Explosives",
"Hermetic Membranes",
"Hazmat Detection Systems",
"Cryoprotectant Solution",
"Plasmoids",
"Electrolytes",
"Oxidizing Compound",
"Bacteria",
"Proteins",
"Biofuels",
"Industrial Fibers",
"Reactive Metals",
"Precious Metals",
"Toxic Metals",
"Chiral Structures",
"Nanites",
"Broadcast Node",
"Integrity Response Drones",
"Nano-Factory",
"Organic Mortar Applicators",
"Recursive Computing Module",
"Self-Harmonizing Power Core",
"Sterile Conduits",
"Wetware Mainframe",
"Mechanical Parts",
"Synthetic Oil",
"Fertilizer",
"Polytextiles",
"Silicate Glass",
"Livestock",
"Viral Agent",
"Biomass",
"Construction Blocks",
"Silicon",
"Rocket Fuel",
"Coolant",
"Guidance Systems",
"Consumer Electronics",
"Superconductors",
"Transmitter",
"Miniature Electronics",
"Planetary Vehicles",
"Robotics",
"Transcranial Microcontrollers",
"Genetically Enhanced Livestock",
"Ukomi Superconductors",
"Data Chips",
"High-Tech Transmitters",
"Vaccines",
"Microorganisms",
"Base Metals",
"Aqueous Liquids",
"Noble Metals",
"Heavy Metals",
"Planktic Colonies",
"Complex Organisms",
"Carbon Compounds",
"Autotrophs",
"Non-CS Crystals",
"Felsic Magma",
"Suspended Plasma",
"Ionic Solutions",
"Noble Gas",
"Reactive Gas",
); $ORENAMES = array_merge($ORENAMES,$IMPORT_ORE); ?>