<?php
    /* 
	 * MiningBuddy  
	 * $Header: /usr/home/mining/cvs/mining/include/html/header-notloggedin.txt,v 1.5 2008/01/03 13:27:19 mining Exp $
	 *
	 * This page was generated by the MiningBuddy, the premier EvE Online mining management
	 * software, that is available free of charge at http://miningbuddy.net
	 *
	 * Copyright (c) 2005-2008 Christian Reiss.
	 * All rights reserved.
	 *
	 * Redistribution and use in source and binary forms,
	 * with or without modification, are permitted provided
	 * that the following conditions are met:
	 *
	 * - Redistributions of source code must retain the above copyright notice,
	 *   this list of conditions and the following disclaimer.
	 * - Redistributions in binary form must reproduce the above copyright
	 *   notice, this list of conditions and the following disclaimer in the
	 *   documentation and/or other materials provided with the distribution.
	 *
	 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
	 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
	 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
	 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT Ssans THE COPYRIGHT
	 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
	 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
	 *  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
	 *  OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
	 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
	 *  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
	 *  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
	 */ 
?>

<html>
<head>

<title>%%SITENAME%%</title>
<link rel="stylesheet" type="text/css" href="include/html/default.css" media="only screen and (min-device-width:481px)" />
<link rel="stylesheet" type="text/css" href="include/html/mobile.css" media="only screen and (max-device-width:480px)" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body bgcolor="#2D2D37" text="#ffffff" link="#ff8a00" vlink="#ff8a00" marginwidth="0" marginheight="0" topmargin="0" leftmargin="0">

%%LOGO%%
<hr>
<br>
