<?php
/* 
	 * MiningBuddy  
	 * $Header: /usr/home/mining/cvs/mining/include/html/header.txt,v 1.21 2008/01/10 18:13:32 mining Exp $
	 *
	 * This page was generated by the MiningBuddy, the premier EvE Online mining management
	 * software, that is available free of charge at http://miningbuddy.net
	 *
	 * Copyright (c) 2005-2008 Christian Reiss.
	 * All rights reserved.
	 *
	 * Redistribution and use in source and binary forms,
	 * with or without modification, are permitted provided
	 * that the following conditions are met:
	 *
	 * - Redistributions of source code must retain the above copyright notice,
	 *   this list of conditions and the following disclaimer.
	 * - Redistributions in binary form must reproduce the above copyright
	 *   notice, this list of conditions and the following disclaimer in the
	 *   documentation and/or other materials provided with the distribution.
	 *
	 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
	 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
	 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
	 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT Ssans THE COPYRIGHT
	 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
	 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
	 *  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
	 *  OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
	 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
	 *  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
	 *  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
	 */ ?>	 
<html>
<head>

<title>%%SITENAME%%</title>
<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
<!-- Latest compiled and minified JavaScript -->
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="include/html/default.js"></script>
<link rel="stylesheet" type="text/css" href="include/html/default.css" media="screen" />
<link rel="stylesheet" type="text/css" href="include/html/%%USERNAME%%.css" />
<link rel="stylesheet" type="text/css" href="include/html/mobile.css" media="handheld" />


<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class='OOG'>

<table width="100%" cellpadding="2" cellspacing="0">
<tr><td bgcolor="">
<a href="%%URL%%">%%LOGO%%</a>
</td>
<td id='userInfo' align="right">
%%PILOT64%%
%%LOGGEDIN%%<br>
%%RANK%%<br>
%%CREDITS%%
</td></tr>
<tr><td colspan="2" >
<hr>
</td></tr>
</table>

<table wcellpadding="2" cellspacing="0" height="75%" >

<tr><td id='menu' valign="top" >
%%MENU%%
</td>
<td id='content' valign="top">

